source "https://rubygems.org"
git_source(:github) {|repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

gem "active_model_serializers"

# railsの起動時間を短縮する（標準gem）
gem "bootsnap", require: false

# MySQLに接続する
gem "mysql2", "~> 0.5"

# pumaサーバーを使えるようにする（標準gem）
gem "puma", "~> 5.0"

# cors設定を管理する
gem "rack-cors"
# rails本体（標準gem）
gem "rails", "~> 7.0.4"

gem "devise"
gem "devise-i18n"
gem "devise_token_auth"
# タイムゾーン情報を提供する（標準gem）
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
# 　環境毎の設置管理を行う
gem "config"

group :development, :test do
  # テスト用データを作成する
  gem "factory_bot_rails"
  gem "faker"
  gem "letter_opener_web"
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"
  gem "rspec-rails"
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end
